version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:3000"
    volumes:
      - .:/app
    command: ["npm", "run", "start"]
