version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: bash -c "sleep 45s && npx prisma migrate deploy ; npm run start"
    restart: unless-stopped
    depends_on:
      - db
  db:
      image: postgres:12-alpine
      container_name: db
      restart: always
      ports:
        - "5432:5432"
      env_file:
        - .env
      volumes:
        - ./postgres-data:/var/lib/postgresql/data

 

